### ISSUE TITLE
Utilise FInputDeviceScope in SendControllerEvents

### ISSUE THREAD

**Issue by JaydenMaalouf** [JaydenMaalouf/JoystickPlugin#10]
As per sswires suggestion on the Slackers Discord - we should utilise the FInputDeviceScope struct to help the engine identify the type of controller being used.

**Comment by brifsttar** [comment]
Whenever I have to use undocumented features, I just go look for example in the engine's source. `FInputDeviceScope` is used for SteamController, XInput and RawInput, maybe those examples can help.

For the link error, I can see that those examples also list `ApplicationCore` as `PrivateDependencyModuleNames` which the plugin currently doesn't have. It's also where `FInputDeviceScope` is defined.

Hope this can be of any help, let me know if I can help more.

**Comment by JaydenMaalouf** [comment]
> I can see that those examples also list `ApplicationCore` as `PrivateDependencyModuleNames`

Yep - that's done it!

Thank you very muchly!
