### ISSUE TITLE
Joysticks don't work with InputKeySelector

### ISSUE THREAD

**Issue by brifsttar** [JaydenMaalouf/JoystickPlugin#18]
Hey @JaydenMaalouf,

We recently discovered that joysticks (as defined in the plugin) don't properly work with the [InputKeySelector](https://docs.unrealengine.com/4.26/en-US/API/Runtime/UMG/Components/UInputKeySelector/) widget.

![image](https://user-images.githubusercontent.com/53508707/139440830-e9251b7c-77a5-4c37-badf-987fd877f8d3.png)

This widget is mostly used to allow [runtime rebinding](https://forums.unrealengine.com/t/mini-tutorial-the-new-blueprint-support-for-runtime-key-binds-controls-remapping-action-mapping/108777), which is extremely useful for joysticks, as there's really no standard way to define axes (e.g. each vendor will give a different index to the "throttle" axis).

The behavior between joysticks and the widget is weird: if the plugin isn't enabled, the widget totally ignores the joystick, which is expected. If the plugin is enabled, the widget apparently can detect part of the joystick, since the widget will correctly toggle if you move an axis, but the related event (`On Key Selected`) doesn't fire.

I can't test this right now as I don't have a joystick, but I've been remotely debugging that with a colleague this morning. We currently have a workaround, so it's not a big issue. But it would be nice to have the ability to rebind joystick axes at runtime.

I could try to implement this myself, but seeing as you seem more at ease around this code than me, I prefer to open an issue first ;-)

**Comment by JaydenMaalouf** [comment]
I’ll have so time in a few days to experiment with this. Definitely would be a nice to have though!

**Comment by Juris3D** [comment]
Hello, was this progressed, please?

**Comment by JaydenMaalouf** [comment]
> Hello, was this progressed, please?

Hey @Juris3D,
Yes I am slowly making progress on this!
It required a decent refactor of the Manager and joystick status but I did manage to get it to work.
I will likely push this in the next update - which I'm hoping will be ready by EOY but cannot make any promises haha

**Comment by JaydenMaalouf** [comment]
Latest beta release solves this issue:
https://github.com/JaydenMaalouf/JoystickPlugin/releases/tag/v1.0.0-beta.14

Please try it out and let me know if there are any issues.

**Comment by JaydenMaalouf** [comment]
This should be completed as part of the 1.0.0 rework
