### ISSUE TITLE
Unable to use the plugon on linux

### ISSUE THREAD

**Issue by MNS26** [JaydenMaalouf/JoystickPlugin#39]
whenever i try and add the plugin it asks to rebuild and fails after roughly 30sec 

![image](https://user-images.githubusercontent.com/53867268/227737060-c06a3aab-8916-4cf0-80b9-48dc192db2e1.png)
![image](https://user-images.githubusercontent.com/53867268/227737096-d24c9b63-6334-41d8-aa3b-39449005e3e9.png)

**Comment by JaydenMaalouf** [comment]
Hello!
Which release of the plugin are you using?

Ensure that you run `GenerateProjectFiles.sh` after copying the plugin to your project. 
Then rebuild the project using make
If there are any errors during the make build, please post them here for me to help investigate!

**Comment by MNS26** [comment]
Im using the latest released zip.
I dont have a `GenerateProjectFiles.sh` bash scrip, i also dont see any logs when it tries to rebuild it

**Comment by JaydenMaalouf** [comment]
I actually found some issues with the contents in master on Linux and have merged in a fix.

I will write some documentation on how to Rebuild the plugin on linux later today.
Hopefully the latest Release fixes your issue though!

**Comment by MNS26** [comment]
the windows zip for 5.1 rebuilt without any issue for linux
