### ISSUE TITLE
Difficulty mapping Thrustmaster

### ISSUE THREAD

**Issue by VitorAbyssal** [JaydenMaalouf/JoystickPlugin#47]
Greetings,

I'm attempting to use a TFlightHotasX with the plugin. While the plugin recognizes it in the Mapping Context as a "Joystick 0" for any button/axis, I would like to have the specific name of the device as I might have other joysticks connected to my project so I can easily distinguish between them.
![image](https://github.com/JaydenMaalouf/JoystickPlugin/assets/82595178/a607ab3b-ae3a-405d-83c9-a5cdaedba991)

I noticed in your Wiki on the Usage page that you indeed have different names showing up instead of just "Joystick 0" but I'm a bit confused on how this should be done. 

These are my current project settings for the plugin: 
![image](https://github.com/JaydenMaalouf/JoystickPlugin/assets/82595178/d5dbfb02-0445-468d-b902-8b91445d2281)

Unlike in the Usage page, I do not have the option to select the key value.

Thank you

**Comment by VitorAbyssal** [comment]
Okay, silly me, I didn't notice the flag "Use Device Name" 😅 . That fixes one issue.

But selecting key value is still not available in the project settings like this:
![image](https://github.com/JaydenMaalouf/JoystickPlugin/assets/82595178/f1ed8a71-ac4d-45c2-8b55-f8e2bd1c610e)

Is this the correct behaviour and should I instead use the Axis index?

**Comment by JaydenMaalouf** [comment]
> Okay, silly me, I didn't notice the flag "Use Device Name" 😅 . That fixes one issue.
> 
> 
> 
> But selecting key value is still not available in the project settings like this:
> 
> ![image](https://github.com/JaydenMaalouf/JoystickPlugin/assets/82595178/f1ed8a71-ac4d-45c2-8b55-f8e2bd1c610e)
> 
> 
> 
> Is this the correct behaviour and should I instead use the Axis index?
> 
>  

Apologies for the confusion with the remapping documentation. I realised now that I have not updated it in some time

The correct process is to use the axis index now, as the key selector was from an older version of the plugin. 

I'll try updating the documentation shortly!

**Comment by VitorAbyssal** [comment]
Thanks for the help!
