### ISSUE TITLE
Linux UE5.3.X fails to build 

### ISSUE THREAD

**Issue by MNS26** [JaydenMaalouf/JoystickPlugin#51]
When trying to rebuild the project after adding the plugin it fails to do so.
The project was already made in 5.3.1.

I also tried the fix mentioned in this issue [_Linker Error when upgrading to 5.3_](https://github.com/JaydenMaalouf/JoystickPlugin/issues/50) but that didnt work either

**Comment by JaydenMaalouf** [comment]
I haven't built the plugin for Linux in some time. I've got an update coming soon that adds Enhanced Input functionality, that might be a requirement for 5.3 as it's on by default now!

**Comment by MNS26** [comment]
Ah that might be it then.

**Comment by JaydenMaalouf** [comment]
I've added a comment in the other thread (#50) that has reference to a PR that will fix the build issues for 5.3.x. Feel free to test the changes yourself!

**Comment by JaydenMaalouf** [comment]
I have released [3.2.0-rc.10](https://github.com/JaydenMaalouf/JoystickPlugin/releases/tag/3.2.0-rc.10) which has fixed the build issues with 5.3

Full release will come out once I merged the fix to master

**Comment by JaydenMaalouf** [comment]
I finally have released [3.3.0](https://github.com/JaydenMaalouf/JoystickPlugin/releases/tag/3.3.0)
Please feel free to raise another issue if you happen to find something!
