### ISSUE TITLE
Joystick Axis and Buttons not working

### ISSUE THREAD

**Issue by MustangEnthusiast51** [JaydenMaalouf/JoystickPlugin#56]
I'm able to assign the joystick in the enhanced input mapper, but I can't choose a specific event. When I choose one, it only shows the device name and the event never fires.
![image](https://github.com/JaydenMaalouf/JoystickPlugin/assets/101068820/c693f3c8-62bd-471f-afeb-5ce0e7d76293)
I'm using UE5.3 and release 3.2 (the experimental one because of the 5.3 build)

**Comment by JaydenMaalouf** [comment]
Thanks for reporting this! I was able to replicate it when a device was plugged in that contained spaces in the name.
I have pushed up a fix as part of #59 
I will have a release candidate for this out shortly!

**Comment by JaydenMaalouf** [comment]
[3.3.0](https://github.com/JaydenMaalouf/JoystickPlugin/releases/tag/3.3.0) is out!
Please feel free to raise another issue if you happen to find something!
