### ISSUE TITLE
FJoystickInputDevice is missing JOYSTICKPLUGIN_API.

### ISSUE THREAD

**Issue by fredzvt-drest** [JaydenMaalouf/JoystickPlugin#57]
On 3.2.0-rc.10, the `FJoystickInputDevice` class is missing the `JOYSTICKPLUGIN_API` macro.

On my code I got a pointer to it through `JoystickSubsystem->GetInputDevice()` but when I called `JoystickInputDevice->GetInstanceIdByKey(Key)` I got the link error: `Error LNK2019 : unresolved external symbol "public: struct FJoystickInstanceId __cdecl FJoystickInputDevice::GetInstanceIdByKey(struct FKey const &)const " (?GetInstanceIdByKey@FJoystickInputDevice@@QEBA?AUFJoystickInstanceId@@AEBUFKey@@@Z) referenced in function "private: bool __cdecl UCPKeyMappingSubsystem::GetKeyOwnerJoystickGuid(struct FKey const &,struct FGuid &)const " (?GetKeyOwnerJoystickGuid@UCPKeyMappingSubsystem@@AEBA_NAEBUFKey@@AEAUFGuid@@@Z)`

After a lot of time banging my head on the wall, I found that this class was never exported on the plugin module.

**Comment by JaydenMaalouf** [comment]
Thanks for pointing this out - I've just merged a commit into the #54 branch
I will hopefully get this release out once I have resolved the other issues people are facing!

**Comment by JaydenMaalouf** [comment]
I have released [3.3.0](https://github.com/JaydenMaalouf/JoystickPlugin/releases/tag/3.3.0)
Please feel free to raise another issue if you happen to find something!
