### ISSUE TITLE
UE 5.3.2 Support?

### ISSUE THREAD

**Issue by jayb8200** [JaydenMaalouf/JoystickPlugin#66]
Hi, I am attempting to get this plugin to work with 5.3.2 but struggling immensely. Is it just not supported yet or am I doing something wrong? One of the errors stated, "Engine modules cannot be compiled at runtime." Any help would be appreciated

**Comment by JaydenMaalouf** [comment]
Hello,
Just wondering, have you installed the plugin via the [Release](https://github.com/JaydenMaalouf/JoystickPlugin/releases/tag/3.3.0) or have you cloned the code directly into your project?
There are some included binaries in the Release that are required for the plugin to work on Windows

**Comment by JaydenMaalouf** [comment]
Closing this out, as Unreal 5.0-5.5 are supported
