### ISSUE TITLE
Recompilation for UE version 5.4.2

### ISSUE THREAD

**Issue by KeinEngelZlat** [JaydenMaalouf/JoystickPlugin#67]
Hi, everyone! When the plugin version is planned for the UE5 version 5.4.2? If the transfer to the new version is not planned or is not planned in the near future, then how can I recompile the plugin on my own? I have not found the source code of the plugin. @JaydenMaalouf

**Comment by JaydenMaalouf** [comment]
Ahh yep
I can compile a release for 5.4 in the next few days
I need to re-setup my build environment as Windows decided to corrupt itself during an update lol

You can technically use the 5.3 version of the binary and just recompile the plugin on project startup. Do note: recompiling might not work if you have a blueprint only project

**Comment by KeinEngelZlat** [comment]
Okay, thanks, we'll be waiting. That is, if the project is made on blueprints, will an error always be shown? And if you create a separate project in C++, then when you add a plugin, it can be transferred to a new version of the engine?

**Comment by KeinEngelZlat** [comment]
Okay, thanks, we'll be waiting. That is, if the project is made on blueprints, will an error always be shown? And if you create a separate project in C++, then when you add a plugin, it can be transferred to a new version of the engine?

**Comment by JaydenMaalouf** [comment]
@KeinEngelZlat  5.4 support is available in version [3.4.0](https://github.com/JaydenMaalouf/JoystickPlugin/releases/tag/3.4.0)

**Comment by KeinEngelZlat** [comment]
> @KeinEngelZlat 5.4 support is available in version [3.4.0](https://github.com/JaydenMaalouf/JoystickPlugin/releases/tag/3.4.0)

Thanks a lot!
