### ISSUE TITLE
No place to bind an axis in the Joystick Input section inside of project settings.

### ISSUE THREAD

**Issue by TobiiCodes** [JaydenMaalouf/JoystickPlugin#70]
This is the setup guide:
![image](https://github.com/user-attachments/assets/a97f549a-9a07-4562-b7ba-13ed6aa2c774)
But this is what is on my screen (UE 5.4.2):
![image](https://github.com/user-attachments/assets/006bd8db-2674-429b-bee7-1091a975d44b)

**Comment by JaydenMaalouf** [comment]
Ah yep. This is just old documentation from version 2.x
The system works the same, it just doesn't need to care about the physical key
The reason behind this was there were times where the Joystick name would cause the Joystick key mapping to be lost by Unreal
So I opted to use the Joystick GUID and an array of the index and the mappings
I do prefer the old system, so might look at going back to it now that the key mapping being lost issue is resolved

**Comment by TobiiCodes** [comment]
But ue5 still wont detect any input from my g920

**Comment by JaydenMaalouf** [comment]
> But ue5 still wont detect any input from my g920

Can you detail the issue a little more?
Does the device show up in the connected devices list (in the settings)?

**Comment by TobiiCodes** [comment]
yes it does but if i put it into input as in axis mappings (binding the steering wheel rotation) then i print that axis float in a blueprint it always returns 0 even tho i turn the wheel

**Comment by JaydenMaalouf** [comment]
> yes it does but if i put it into input as in axis mappings (binding the steering wheel rotation) then i print that axis float in a blueprint it always returns 0 even tho i turn the wheel

To clarify, in your screenshot, that is an input REmapping configuration. Which is for if your joystick does not present pressed in a standard 0-1 float. ie. my pedals come in 1:-1 (yes inverted), so the remapping is necessary for me

What happens if you have no input remapping and just use the axis event?

**Comment by TobiiCodes** [comment]
Still no input, the screen shot isnt really an issue anymore, just that it always returns 0  and detects 0 input

**Comment by JaydenMaalouf** [comment]
> Still no input, the screen shot isnt really an issue anymore, just that it always returns 0  and detects 0 input

Can you please provide some more screenshots on your device in the Connected Devices settings page and how you're trying to access the axis value?

I just want to make sure that everything is setup correctly 

Also, can you enable logs (within the Joystick settings) and restart the editor?
Then if possible, copy the content to a pastebin (obfuscate the PI/PII from logs) and send the link here

**Comment by TobiiCodes** [comment]
Logs are enabled, where do i find them?

here is the joystick input settings:
![image](https://github.com/user-attachments/assets/98df8d7b-e31c-4eb9-981c-d2e38b16b9b5)

steering2 binded to the axis 0:
![image](https://github.com/user-attachments/assets/db2c96ff-17bd-4c18-b80f-2de7eef8c00e)

printing the float value of the axis:
![image](https://github.com/user-attachments/assets/15988c60-ad7e-4812-8aa4-0d40f41b4f42)

always prints 0 no matter if i turn the wheel, press gass pedal, brakes or clutch.
![image](https://github.com/user-attachments/assets/985b515f-a2b5-4d57-97a2-23665a278a85)

**Comment by JaydenMaalouf** [comment]
> Logs are enabled, where do i find them?

Logs go to `<projectDirectory>/Saved/Logs/`
Usually the last modified file is the one to upload

> here is the joystick input settings:
> 
> ![image](https://github.com/user-attachments/assets/98df8d7b-e31c-4eb9-981c-d2e38b16b9b5)

Please expand this drop down
![image](https://github.com/user-attachments/assets/c2e04e8a-ccca-4263-ba7c-9c1155f7bb47)

> steering2 binded to the axis 0:
> 
> ![image](https://github.com/user-attachments/assets/db2c96ff-17bd-4c18-b80f-2de7eef8c00e)

That mapping is not necessary as it's bound to -1 which is not a valid axis index. I would suggest removing it

**Comment by TobiiCodes** [comment]
LOG:
[SimRacing.log](https://github.com/user-attachments/files/16393236/SimRacing.log)

Connected devices:
![image](https://github.com/user-attachments/assets/a86a453d-80f3-40fe-accd-7414e0f9b870)

**Comment by JaydenMaalouf** [comment]
Okay, so which Axis are you binding to again?
I assume `LogitechGHUBG920DrivingForceRacingWheelUSB`?

**Comment by TobiiCodes** [comment]
Yes

**Comment by TobiiCodes** [comment]
FIX:
Do not run input mode ui only!
![image](https://github.com/user-attachments/assets/abaa42b1-73b3-40b5-a187-c423bfcaa707)

Turn off consume input on inputaxis!
![Uploading image.png…]()
