### ISSUE TITLE
Documentation of different FFB effects

### ISSUE THREAD

**Issue by freshefisch** [JaydenMaalouf/JoystickPlugin#76]
An overview of all the different force feedback effects with their usecases und parameters would be amazing.

For example I figured out that the "condition" effect can be used to make the steering wheel spring back to center. The strength can then be varied by adjusting "Effect Right/Left Sat"

**Comment by JaydenMaalouf** [comment]
Took some time to get around to this but I've documented some things here:
https://github.com/JaydenMaalouf/JoystickPlugin/wiki/Effects

It's a shame there isn't much documentation around this. I built this plugin with the intention on building out these effects for my own project but I still haven't got something I'm happy with haha
