### ISSUE TITLE
new build needed or please provide missing files. 

### ISSUE THREAD

**Issue by steamjunkie** [JaydenMaalouf/JoystickPlugin#79]
req all source code, for building for unreal 5.5 missing files.  or please build it for unreal 5.5

thanks.

**Comment by JaydenMaalouf** [comment]
5.5 support will come in the next major release
I will also update the example project to support this

**Comment by JaydenMaalouf** [comment]
5.5 support is available in the latest release candidate
Please test it out and raise any issues you come across
Thanks!
https://github.com/JaydenMaalouf/JoystickPlugin/releases/tag/3.5.0-rc.23
