### ISSUE TITLE
Add some example effects to the plugin

### ISSUE THREAD

**Issue by JaydenMaalouf** [JaydenMaalouf/JoystickPlugin#8]
This is more of a nice to have for anyone that wants true plug n play

**Comment by Gmacree** [comment]
Could you also add a demo project that show how to make force feedback I personally don't really understand the way it works

**Comment by JaydenMaalouf** [comment]
> Could you also add a simple demo project that show how to make force feedback I personally don't really understand the way it works 

I should have some time this weekend to put something together in a separate repo

**Comment by Juris3D** [comment]
I just leave a not here, that, from my perspective also - having a ready example is always a good idea. For both testing, and - understanding.

**Comment by JaydenMaalouf** [comment]
> Any news on examples on how to send forcefeedback effects ?

I'm currently doing a bit of rework on FFB as the current implementation has some issues when multiple devices come into play (ie. Thrustmaster Shifter + Wheel). Once I have a solid solution, I'll make some example effects.

**Comment by gotleg** [comment]
OK great, thank you very much. If I can be any help ;)

**Comment by gotleg** [comment]
Don't wanna push you but do you have any idea of when it could be available ? We alreay use you plugin for driving and i'm impatient to start coding force feedback :)
The way your plugin integrates to unreal is way cleaner than any other solution out there, keep going 👍

**Comment by KeinEngelZlat1992** [comment]
Do you have the opportunity to add an example of the FFB implementation to your plugin? We managed to figure out all the nuances, except for the implementation of the FFB, it remains only to get an understanding of how force feedback is created.

**Comment by KeinEngelZlat1992** [comment]
@JaydenMaalouf Do you have the opportunity to add an example of the FFB implementation to your plugin? We managed to figure out all the nuances, except for the implementation of the FFB, it remains only to get an understanding of how force feedback is created.

**Comment by JaydenMaalouf** [comment]
This is now complete
Example project can be found here:
https://github.com/JaydenMaalouf/JoystickExample
