### ISSUE TITLE
Unreal doesn't come with the Windows compiled SDL

### ISSUE THREAD

**Issue by JaydenMaalouf** [JaydenMaalouf/JoystickPlugin#9]
Look into how we can use the plugin on marketplace versions of Unreal as apparently these don't come with SDL for Windows

**Comment by brifsttar** [comment]
I'm c/p'ing what I posted on the other issue.

>I guess you could ship the lib yourself and install (e.g. copy) it to the engine in the plugin's Build.cs in case it doesn't exist yet. Definitely not a nice fix though.
>
>Or raise the issue to Epic, it's weird they ship Linux but not Windows, maybe it's just a mistake on their part. I'm not sure if the engine's own packaging is open-source, but if so, a PR could be made to add the lib to shipping engine builds. I'll try to look that up when I have time.

I'm a total noob when it comes to engine builds themselves, but from what I gather, all engine plugins that have an `AddEngineThirdPartyPrivateStaticDependencies(Target, "SDL2");` entry in their `Build.cs` file do so only if the target is Linux. So I'm guessing the UBT therefore automatically only includes SDL2 for Linux as it's the only platform that actually requires it for the engine to work.

If that's correct, it means you can't easily make a PR for the engine to include the SDL2 Windows lib; you'd have to actually have an engine plugin rely on it. I could therefore totally understand Epic not wanting to redistribute anything they don't actually need.

**Comment by JaydenMaalouf** [comment]
@brifsttar bang on the money.

The solution works for custom built Engine because the build scripts will recompile SDL2 for the end-user.

I think the alternative would be - on Windows Platforms atleast, we utilise the Windows.Gaming.Input framework. This framework has the same ForcedFeedback effects as SDL2 (not sure which one actually wraps which lol).

This would require a slight restructure of the plugin but would allow all platforms to utilise the plugin without weird compilation setups.

Thoughts?

**Comment by brifsttar** [comment]
> not sure which one actually wraps which lol

SDL wraps the Windows framework.

> Thoughts?

In my opinion, it's weird to have a plugin use SDL for Linux and Windows.Gaming.Input for Windows. I'd either use SDL for all, or drop Linux support.

> This would require a slight restructure of the plugin

Are you sure about that? From my point of view, you'd have to re-do what SDL did, which is have multiple implementation of all your API (mostly BP/assets) for all target platform (Windows, Linux). Which basically means, re-implementing the whole plugin without SDL for Windows. If I understand that correctly, it's a large amount of work.

In the meantime, I've implemented my first "ship & copy" suggestion, but I'm having an issue with DLL loading. I know how to solve it (manually loading the DLL in `StartupModule`), but I'm wondering why you don't have the issue yourself. Did you move the SDL2 dll outside of its default directory (`$(EngineDir)/Binaries/ThirdParty/SDL2/Win64/SDL2.dll`) to a location that UE browse for loading DLLs, so you don't have to load it yourself?

**Comment by JaydenMaalouf** [comment]
@brifsttar I completely agree - not just because it would break the entire setup of the existing plugin, but it just doesn't make sense when SDL already supports both platforms.

> Are you sure about that?

It was like 2am when I wrote that, it's definitely not a slight reimplementation hahaha

> I'm wondering why you don't have the issue yourself

I have the EA2 git branch of Unreal Engine 5. I didn't modify it in any way, just like having the code there if I need to mess with things (plus I like bringing in fixes from other devs).

All I did was a full engine compilation and the required files appeared in my Engine folder.

The plugin doesn't need the SDL2.dll file - it actually wants the `SDL2.lib` file instead (`$(EngineDir)/Source/ThirdParty/SDL2/SDL-gui-backend/lib/Win64').

So I think I'll create several releases for the plugin using a CI/CD process to compile everything (including the SDL lib). Then users can just copy the lib file into their Engine directory? or I can change my Build.cs to look in the ThirdParty directory for it (which I am not a fan of).

**Comment by brifsttar** [comment]
> The plugin doesn't need the SDL2.dll file - it actually wants the SDL2.lib file instead ($(EngineDir)/Source/ThirdParty/SDL2/SDL-gui-backend/lib/Win64/SDL2.lib). This is because we are using the AddEngineThirdPartyPrivateStaticDependencies function.

I really don't get how any of this works. The Windows SDL2 lib built from the engine is dynamic, i.e. it needs a DLL. You can check that from `SDL2.Build.cs`

https://github.com/EpicGames/UnrealEngine/blob/5.0.0-early-access-2/Engine/Source/ThirdParty/SDL2/SDL2.Build.cs#L39-L45

And as expected from my side, if I don't load the DLL manually, the editor crashes on startup. Once I load manually (see https://github.com/brifsttar/JoystickPlugin/commit/90b6812dcf4f8534e18f087a4e27bfd66338ccbd), it works perfectly fine (at least it succesfully loads, I haven't tried the plugin yet).

What I don't get is what on earth it works for you. `AddEngineThirdPartyPrivateStaticDependencies` means you link statically to the SDL2 *UE4 module* (i.e. the one defined in `SDL2.Build.cs`), not to SDL2 itself. As you can see in the aforementioned `SDL2.Build.cs`, the module links dynamically to SDL2 itself.

The only reason I can think of is if you have `SDL2.dll` on your path, or at least the path UE4 checks for DLL. I've dealt with quite a few DLL-loading plugins, and the only times I don't have to manually load DLLs are if they're in the path. Or, of course, if we're statically linking, but that's not the case here.

In any case, I have a develop branch on my fork (that's rebased on yours), where I added 2 commits to successfully load the plugin on a launcher install of UE4.

I just added the lib+dll to the plugin, and from the `Build.cs` I move the lib to the folder where the SDL2 module expects it. I thought moving the DLL to the same folder where it's output on a build would make UE load it automatically, but that doesn't work. So I reverted to the old way of loading the DLL manually.

I'm definitely not a fan of this solution either, it's an ugly hack. But I don't see any viable alternative at the moment. At least for now it'll allow me to test all of your work, which is what I wanted initially.

**Comment by JaydenMaalouf** [comment]
@brifsttar 
Okay so I'm an idiot. I likely added the SDL2.dll sometime before I started this plugin (file says added like 3 weeks ago 🤦) when I was first looking into using SDL2.

So yes, both the SDL2.dll and SDL2.lib are required for full compilation.

The biggest concern I have is that the UE4 version of SDL2 is modified and doesn't match the DLL online - do you think this will prove to be an issue if I start packaging the plugin with the public versions?

Or should I still go down the route of a CI/CD process to compile UE version of SDL2 and put that into the Releases?

**Comment by brifsttar** [comment]
@JaydenMaalouf 

> The biggest concern I have is that the UE4 version of SDL2 is modified and doesn't match the DLL online - do you think this will prove to be an issue if I start packaging the plugin with the public versions?

I also worried that UE's version had changes, but obviously it doesn't have much since you've already ported this plugin from "BYO" SDL2 to "UE" SDL2 without much issue. Going through the reverse process should not be much of an issue.

As I see it, their are two choices to be made:
* Which SDL2 source to use
* How to ship it

For which SDL2 version to use, I honestly don't have an opinion. From the look of it, UE's SDL2 is 2.0.12, whereas the latest SDL2 is 2.0.14. From the git log, it seems UE's SDL2 has some very slight changes (bugfixes) that shouldn't change much for the joystick side of things.

For how to ship it, no matter which source you use, you can either set up a CI/CD to build it (either via UE rebuild or vanilla SDL2 rebuild) and bundle it with the plugin on releases, or just add binaries to the repo. If you use vanilla SDL2, you could probably just grab a pre-built release, if you use UE's, just copy the dll/lib from a source build. But in any cases, I'd recommend to ship a plugin that in itself works, and doesn't require the user to take extra steps (e.g. copy a lib). Especially if you intend on publishing it to the Marketplace at some point, because it then becomes a requirement.

Bascially, on my `develop` branch, I chose UE's SDL2 for the first point, and "ship binary in repo" in the second. I did that mostly out of lazyness, which is the main factor behind all of my decisions :D

**Comment by brifsttar** [comment]
FYI, it's common practice to bundle third party dependencies (bin, inc, lib) with plugins that requires it. Having submitted a plugin the the Marketplace this weekend, I can even tell you that there's a [whole section](https://www.unrealengine.com/en-US/marketplace-guidelines#273) in the Marketplace Guidelines about it.

> Third party dependencies may only be used with proof of permission and must be placed in a ThirdParty folder located inside the Source folder.

It's what I do with most plugins I maintain/contribute to, and it's also what's done in UE's plugins. But the upstream version of JoystickPlugin was a complete mess on that point, so it's definitely not easy to sort this out.

**Comment by JaydenMaalouf** [comment]
Good news!
I have setup a build machine for the plugin. Currently rebuilding 4.26 Engine - will take quite a while haha

Side note: Pulling the source, then running Setup.bat actually pulls the SDL2.dll and SDL2.lib from somewhere - so I don't even need to do a full engine build to have these files on hand.

Once the engine is compiled, I will setup the CI/CD process which should mean I'll have a 1.0.0-beta in the next few days!

**Comment by JaydenMaalouf** [comment]
Got the full CI/CD working, with copying the required dll and lib files to the plugin builds but I can't for the life of me get the dlls to load at runtime - are you able to show me your Build.cs file to load the files from Binaries/ThirdParty directory?
@brifsttar

**Comment by brifsttar** [comment]
@JaydenMaalouf 
The DLL loading occurs at runtime, so in the C++ code. You can check my code here: https://github.com/brifsttar/JoystickPlugin/commit/90b6812dcf4f8534e18f087a4e27bfd66338ccbd

Also, for proper implementation, you need to add two lines ([see here](https://github.com/brifsttar/JoystickPlugin/blob/a1d2ae2e4c78b0f4165e060d35d1576c59c73a34/Source/JoystickPlugin/JoystickPlugin.Build.cs#L55-L56)) in the Build.cs, namely `RuntimeDependencies` and `PublicDelayLoadDLLs`. Otherwise, the DLL isn't bundled on the packaged game, which leads to a crash. You might want to test that too, because when DLL are involved, getting it to work in editor is often easier than in a packaged product.

**Comment by JaydenMaalouf** [comment]
@brifsttar 
Yeah I think that's where most of my issues are stemming from.

It works fine in Editor but once compiled, it's not the right structure and UE throws a fit. 

I'll keep playing tomorrow.. hopefully can solve it haha

**Comment by JaydenMaalouf** [comment]
Btw the branch is [here](https://github.com/JaydenMaalouf/JoystickPlugin/tree/azure-pipelines)

**Comment by brifsttar** [comment]
@JaydenMaalouf 

> I'll keep playing tomorrow.. hopefully can solve it haha
I'm not too worried, I can definitely help here.

From what I see in your branch:
* You're indeed missing the DLL loading in C++
* [`PublicDelayLoadDLLs`](https://github.com/JaydenMaalouf/JoystickPlugin/blob/azure-pipelines/Source/JoystickPlugin/JoystickPlugin.Build.cs#L42) doesn't take a full path as parameter, only DLL filename (though I have no clue what this directive does, even after looking at source)
* I honestly don't know if [`$(PluginDir)`](https://github.com/JaydenMaalouf/JoystickPlugin/blob/azure-pipelines/Source/JoystickPlugin/JoystickPlugin.Build.cs#L44) is a valid macro, so you might want to stick with something like `Path.Combine(PluginDirectory, "ThirdParty", "SDL2", "Win64", "SDL2.dll")`

I don't have time to test this much more today, but maybe tomorrow. If not, later in the week will do.

**Comment by JaydenMaalouf** [comment]
@brifsttar 

Thanks for that!

First release is finally up - albeit beta release.
https://github.com/JaydenMaalouf/JoystickPlugin/releases/tag/v1.0.0-beta.1

Looks like its loading correctly on a the marketplace version of UE4 (4.26)
Hopefully this is setup correctly

Let me know if this works for you! :D

Also, if anyone wants specific versions of the Engine (within 3 versions of the current most Engine version) lemme know!

**Comment by brifsttar** [comment]
@JaydenMaalouf 
Congrats on the first release! I gave it a quick try (Editor only), and it works perfectly fine :+1:

The only issue I see is for people working from source instead of release (like me), we have to manually add the DLL/lib since it's not within the repo itself. I've source controled the DLL in my fork to workaround this, so it's not a big deal, but anyone who would want to contribute to this plugin might have some difficulty getting started since a basic clone of this repo doesn't work out-of-the-box.

**Comment by JaydenMaalouf** [comment]
Thanks @brifsttar! And thanks for all your help and suggestions!

I think the main issue with my approach is that I'm using the SDL version specific to the Engine release, that way I can use the Engine included headers instead of fully byo - I could theoretically switch to fully byo but I would then need to maintain SDL versions and I really don't have the time for that haha

Each engine release has their own version of SDL. Which means each release will include the necessary binaries for that engine version (this is handled by the ci).

The main reason I stuck by this is because there are several changes and fixes that occur between SDL versions include in UE releases.

I'll probably add instructions to downloading the engine specific versions as a middle ground on getting started - maybe even zip the SDL binaries separately in a release for easy downloading?

**Comment by brifsttar** [comment]
@JaydenMaalouf 

> maybe even zip the SDL binaries separately in a release for easy downloading?

That sounds great, plus a section in the README about getting started from source, where you just mention that after a clone, you need to download+unzip the archive from the release page. I think that would be more than enough, as anyone who'd go so far as to clone the repo would *probably* read the README and manage to follow those simple steps.

**Comment by JaydenMaalouf** [comment]
Closing this as the Build system now handles the inclusion of binaries.
